### ISSUE TITLE
editors welcomed

### ISSUE THREAD

**Issue by adam-gruer** [ropenscilabs/learngganimate#2]
We'd love people to proof read and edit the prose.
I have been not worrying too much about typos or grammar as I’ve gone along so the text could benefit from some TLC from a kind editor

**Comment by jlbeaudry** [comment]
I'm a novice R user and have never even tried to use gganimate. I'd be happy to walk through your tutorials if you want to see if they work for someone who knows nothing. (I can't stop myself from editing either, so that's a nice side benefit...). 

I won't be able to get to it for a couple of weeks though, so let me know if that's a problem.

**Comment by annaquaglieri16** [comment]
That would be super helpful @jlbeaudry!

**Comment by adam-gruer** [comment]
Yes thanks so much @jlbeaudry 🥇   anytime you are able to contribute is most welcome.  The crew hope to keep adding to this project as life permits and hopefully content from other contributors will find its way here as well so I think hope there'll always be something that good use some TLC.  If you have any questions at all reach out to us here.  I hope to add a guide for contributors to the project soon.  I'll post a link here.

**Comment by lizardbreath40** [comment]
I can help out here as well, if it's still needed.

**Comment by adam-gruer** [comment]
There hasn't been much/any work on this repo since the ozunconf but contributions are still welcome .  The generated work is still available on the internet so If you are interested i adding any updates I think that is great.
